version: "3.7"
services:

  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - internal
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    command:
      - --log.level=INFO
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker
      - --providers.file.directory=/rules
      - --providers.docker.exposedbydefault=false
      - --global.sendAnonymousUsage=true
      - --api
      - --certificatesresolvers.cloudflare.acme.email=${FW_EMAIL}
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.storage=/acme.json
      - --serverstransport.insecureSkipVerify=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.options=default
      - traefik.http.routers.traefik.middlewares=auth,securityheaders
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAINNAME}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAINNAME}
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.auth.basicauth.users=${HTTP_USERNAME}:${HTTP_PASSWORD}
      - traefik.http.middlewares.sslredirect.redirectscheme.scheme=https
      - traefik.http.middlewares.securityheaders.headers.forceSTSHeader=true
      - traefik.http.middlewares.securityheaders.headers.stsPreload=true
      - traefik.http.middlewares.securityheaders.headers.stsSeconds=315360000
      - traefik.http.middlewares.securityheaders.headers.stsIncludeSubdomains=true
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.middlewares=sslredirect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/shared:/shared
      - $USERDIR/docker/traefik/acme/acme.json:/acme.json
      - $USERDIR/docker/traefik/rules:/rules 

  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/duplicati:/config
      - ${USERDIR}:/source
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.duplicati.rule=Host(`duplicati.${DOMAINNAME}`)
      - traefik.http.routers.duplicati.entrypoints=https
      - traefik.http.routers.duplicati.tls=true
      - traefik.http.routers.duplicati.tls.options=default
      - traefik.http.routers.duplicati.middlewares=auth,securityheaders
      - traefik.http.services.duplicati.loadbalancer.server.port=8200
      - traefik.docker.network=traefik_proxy

  adguard-home:
    image: adguard/adguardhome
    container_name: adguard-home
    restart: always
    volumes:
      - ${USERDIR}/docker/adguard:/opt/adguardhome/work
      - ${USERDIR}/docker/adguard:/opt/adguardhome/conf
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.${DOMAINNAME}`)
      - traefik.http.routers.adguard.entrypoints=https
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.tls.options=default
      - traefik.http.routers.adguard.middlewares=securityheaders
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - traefik.docker.network=traefik_proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpma.rule=Host(`phpma.${DOMAINNAME}`)
      - traefik.http.routers.phpma.entrypoints=https
      - traefik.http.routers.phpma.tls=true
      - traefik.http.routers.phpma.tls.options=default
      - traefik.http.routers.phpma.middlewares=securityheaders
      - traefik.http.services.phpma.loadbalancer.server.port=80
      - traefik.docker.network=traefik_proxy
      
  cadvisor:
    image: gcr.io/google-containers/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.cadvisor.rule=Host(`cadvisor.${DOMAINNAME}`)
      - traefik.http.routers.cadvisor.entrypoints=https
      - traefik.http.routers.cadvisor.tls=true
      - traefik.http.routers.cadvisor.tls.options=default
      - traefik.http.routers.cadvisor.middlewares=auth,securityheaders
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080
      - traefik.docker.network=traefik_proxy

  flexget:
    image: wiserain/flexget
    container_name: flexget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FG_WEBUI_PASSWD=${FLEXGET_PASSWORD}
      - FG_LOG_LEVEL=INFO
    volumes:
      - ${USERDIR}/docker/flexget:/config
      - /storage:/storage
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.flexget.rule=Host(`flexget.${DOMAINNAME}`)
      - traefik.http.routers.flexget.entrypoints=https
      - traefik.http.routers.flexget.tls=true
      - traefik.http.routers.flexget.tls.options=default
      - traefik.http.routers.flexget.middlewares=securityheaders
      - traefik.http.services.flexget.loadbalancer.server.port=5050
      - traefik.docker.network=traefik_proxy
      
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - ${USERDIR}/docker/transmission:/config
      - ${USERDIR}/TransmissionDL:/downloads
    ports:
      - 55700:55700
      - 9091:9091
      - 55700:55700/udp
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAINNAME}`)
      - traefik.http.routers.transmission.entrypoints=https
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.tls.options=default
      - traefik.http.routers.transmission.middlewares=securityheaders
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.docker.network=traefik_proxy

  filebot-node:
    image: rednoah/filebot:node
    container_name: filebot-node
    restart: always
    volumes:
      - ${USERDIR}/docker/filebot:/data
      - ${USERDIR}/TransmissionDL:/downloads
      - /storage:/storage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebot.rule=Host(`filebot.${DOMAINNAME}`)
      - traefik.http.routers.filebot.entrypoints=https
      - traefik.http.routers.filebot.tls=true
      - traefik.http.routers.filebot.tls.options=default
      - traefik.http.routers.filebot.middlewares=auth,securityheaders
      - traefik.http.services.filebot.loadbalancer.server.port=5452
      - traefik.docker.network=traefik_proxy

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.options=default
      - traefik.http.routers.portainer.middlewares=securityheaders
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.docker.network=traefik_proxy

  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    networks:
      - internal
      
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    restart: always
    volumes:
      - ${USERDIR}/docker/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    networks:
      - traefik_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.unifi.rule=Host(`unifi.${DOMAINNAME}`)
      - traefik.http.routers.unifi.entrypoints=https
      - traefik.http.routers.unifi.tls=true
      - traefik.http.routers.unifi.tls.options=default
      - traefik.http.routers.unifi.middlewares=securityheaders
      - traefik.http.services.unifi.loadbalancer.server.port=8443
      - traefik.http.services.unifi.loadbalancer.server.scheme=https
      - traefik.docker.network=traefik_proxy

  emby:
    container_name: emby
    restart: always
    image: emby/embyserver:beta
    volumes:
      - ${USERDIR}/docker/emby:/config
      - /storage:/storage
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 8096:8096/tcp
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - GIDLIST=${PGID},44
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.emby.rule=Host(`media.${DOMAINNAME}`)
      - traefik.http.routers.emby.entrypoints=https
      - traefik.http.routers.emby.tls=true
      - traefik.http.routers.emby.tls.options=default
      - traefik.http.routers.emby.middlewares=securityheaders
      - traefik.http.services.emby.loadbalancer.server.port=8096
      - traefik.docker.network=traefik_proxy

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/mariadb:/config
    networks:
      - internal

  nginx-frank:
    image: linuxserver/nginx
    container_name: nginx-frank
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/nginx/frankw:/config
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.frank.rule=Host(`${DOMAINNAME}`)
      - traefik.http.routers.frank.entrypoints=https
      - traefik.http.routers.frank.tls=true
      - traefik.http.routers.frank.tls.options=default
      - traefik.http.routers.frank.middlewares=securityheaders
      - traefik.docker.network=traefik_proxy

  nginx-fmw:
    image: linuxserver/nginx
    container_name: nginx-fmw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/nginx/fmw:/config
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.fmw.rule=Host(`${FMWDOMAINNAME}`)
      - traefik.http.routers.fmw.entrypoints=https
      - traefik.http.routers.fmw.tls=true
      - traefik.http.routers.fmw.tls.options=default
      - traefik.http.routers.fmw.tls.certresolver=cloudflare
      - traefik.http.routers.fmw.tls.domains[0].main=${FMWDOMAINNAME}
      - traefik.http.routers.fmw.tls.domains[0].sans=*.${FMWDOMAINNAME}
      - traefik.http.routers.fmw.middlewares=securityheaders
      - traefik.docker.network=traefik_proxy

  nginx-thcuk:
    image: linuxserver/nginx
    container_name: nginx-thcuk
    environment:
      - PUID=1001
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/thc:/config
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.thcuk.rule=Host(`${THCDOMAINNAME}`)
      - traefik.http.routers.thcuk.entrypoints=https
      - traefik.http.routers.thcuk.tls=true
      - traefik.http.routers.thcuk.tls.options=default
      - traefik.http.routers.thcuk.tls.certresolver=cloudflare
      - traefik.http.routers.thcuk.middlewares=securityheaders
      - traefik.docker.network=traefik_proxy

  deluge:
    image: linuxserver/deluge:5b398f77-ls22
    restart: unless-stopped
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/deluge:/config
      - ${USERDIR}/Deluge:/downloads
    ports:
      - "54700:54700"
      - "54700:54700/udp"
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`deluge.${DOMAINNAME}`)
      - traefik.http.routers.deluge.entrypoints=https
      - traefik.http.routers.deluge.tls=true
      - traefik.http.routers.deluge.tls.options=default
      - traefik.http.routers.deluge.middlewares=securityheaders
      - traefik.http.services.deluge.loadbalancer.server.port=8112
      - traefik.docker.network=traefik_proxy

  calibre-web:
    image: linuxserver/calibre-web
    restart: unless-stopped
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ${USERDIR}/docker/calibre/config:/config
      - ${USERDIR}/docker/calibre/books:/books
    networks:
      - traefik_proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`calibre.${DOMAINNAME}`)
      - traefik.http.routers.calibre.entrypoints=https
      - traefik.http.routers.calibre.tls=true
      - traefik.http.routers.calibre.tls.options=default
      - traefik.http.routers.calibre.middlewares=auth,securityheaders
      - traefik.http.services.calibre.loadbalancer.server.port=8083
      - traefik.docker.network=traefik_proxy

  # timemachine:
  #   image: mbentley/timemachine:smb
  #   container_name: timemachine
  #   hostname: timemachine
  #   environment:
  #     - TM_UID=${PUID}
  #     - TM_GID=${PGID}
  #     # - TM_USERNAME=frank
  #     # - TM_GROUPNAME=docker
  #     - DEBUG_LEVEL="10"
  #   volumes:
  #     - /mnt/timemachine:/opt/timemachine
  #   networks:
  #     - macvlan1

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  internal:
    external:
      name: internal
  macvlan1:
    external:
      name: macvlan1  